apiVersion: apps/v1
kind: Deployment
metadata:
  name: Todo-Frotend
  labels:
    app: App
spec:
  replicas: 3
  selector:
    matchLabels:
      app: App
  template:
    metadata:
      labels:
        app: App
    spec:
      containers:
      - name: App
        image: todo-frontend:latest
        ports:
        - containerPort: 80
